export {default as Navbar ,} from './navbar/Navbar'
export {default as Cryptocurrencies ,} from './Cryptocurrencies/Cryptocurrencies'
export {default as Homepage ,} from './homepage/Homepage'
export {default as CryptoDetails ,} from './CryptoDetails/CryptoDetails'
export {default as News ,} from './News/News'
export {default as Exchanges ,} from './exchanges/Exchanges'